---
title: "week10_part1"
author: "Kimberlee Wong"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Part 1

1. When running the command PRAGMA index_list('Bird_nests');, it shows  the table has an existing index created by the primary key, Nest_ID. But, this index isn't used in the query because the filtering conditions in the WHERE clause don't use the Nest_ID column. Instead, the query is filtered based on other specifications.

Running the EXPLAIN QUERY PLAN (query from assignment) command in SQLite confirms this is true, as it returns --SCAN Bird_nests, indicating that a full table scan is done instead of using an index. This confirms that no index is being used for the query.

2. Adding an index to a column not referenced in the WHERE clause will not benefit the query performance because the database does not need to search or filter based on that column. So, the index would not be used to narrow down the query results.